services:

  database:
    container_name: word_search_db
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: eden
      POSTGRES_PASSWORD: examplepassword
      POSTGRES_DB: wordsearch
    volumes:
      - word_search_db_data:/var/lib/postgresql/data
    ports:
      - 3535:5432
      
  api:
    container_name: word_search_api
    build:
      dockerfile: WordSearchBattleAPI/Dockerfile
      context: .
    ports:
      - 2943:8080
   
volumes:
  word_search_db_data: